// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OpenSlalom.Data;

#nullable disable

namespace OpenSlalom.Data.Migrations
{
    [DbContext(typeof(OpenSlalomDbContext))]
    [Migration("20260713103701_AddBidirectionalSyncMetadata")]
    partial class AddBidirectionalSyncMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OpenSlalom.Data.Entities.Disziplin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("disziplin");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("disziplin", (string)null);
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Fahrer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at_utc");

                    b.Property<DateOnly?>("Geburtsdatum")
                        .HasColumnType("date")
                        .HasColumnName("geburtsdatum");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Nachname")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nachname");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("VereinId")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_verein");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("vorname");

                    b.HasKey("Id");

                    b.HasIndex("VereinId");

                    b.ToTable("fahrer", (string)null);
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.FahrerImTraining", b =>
                {
                    b.Property<int>("TrainingId")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_training");

                    b.Property<int>("FahrerId")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_fahrer");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("TrainingId", "FahrerId");

                    b.HasIndex("FahrerId");

                    b.ToTable("fahrer_im_training", (string)null);
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Kart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Chassis")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Chassis");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at_utc");

                    b.Property<int>("DisziplinId")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_disziplin");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Motor")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Motor");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("VereinId")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_verein");

                    b.HasKey("Id");

                    b.HasIndex("DisziplinId");

                    b.HasIndex("VereinId");

                    b.ToTable("karts", (string)null);
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.SyncState", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("LastSyncUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("last_sync_utc");

                    b.HasKey("Id");

                    b.ToTable("sync_state", (string)null);
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Training", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("beschreibung");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at_utc");

                    b.Property<int>("DisziplinId")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_disziplin");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("VereinId")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_verein");

                    b.Property<int>("WetterId")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_wetter");

                    b.Property<DateOnly>("Zeitpunkt")
                        .HasColumnType("date")
                        .HasColumnName("zeitpunkt");

                    b.HasKey("Id");

                    b.HasIndex("DisziplinId");

                    b.HasIndex("VereinId");

                    b.HasIndex("WetterId");

                    b.ToTable("training", (string)null);
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Trunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int?>("Pf")
                        .HasColumnType("int")
                        .HasColumnName("pf");

                    b.Property<int?>("Runde")
                        .HasColumnType("int")
                        .HasColumnName("runde");

                    b.Property<double?>("Rundenzeit")
                        .HasColumnType("double")
                        .HasColumnName("rundenzeit");

                    b.Property<int?>("Tf")
                        .HasColumnType("int")
                        .HasColumnName("tf");

                    b.Property<int?>("TstintId")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_tstint");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("TstintId");

                    b.ToTable("trunden", (string)null);
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Tstint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime")
                        .HasColumnName("datum");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at_utc");

                    b.Property<int>("FahrerId")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_fahrer");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int")
                        .HasColumnName("fk_id_training");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("FahrerId");

                    b.HasIndex("TrainingId");

                    b.ToTable("tstints", (string)null);
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Verein", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("MitgliedsNummer")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("mitglieds_nummer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Vereinsname")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasDefaultValue("")
                        .HasColumnName("vereinsname");

                    b.HasKey("Id");

                    b.ToTable("vereine", (string)null);
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Wetter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("wetter");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime")
                        .HasColumnName("deleted_at_utc");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("updated_at_utc")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.ToTable("wetter", (string)null);
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Fahrer", b =>
                {
                    b.HasOne("OpenSlalom.Data.Entities.Verein", "Verein")
                        .WithMany("Fahrer")
                        .HasForeignKey("VereinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_fahrer_vereine");

                    b.Navigation("Verein");
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.FahrerImTraining", b =>
                {
                    b.HasOne("OpenSlalom.Data.Entities.Fahrer", "Fahrer")
                        .WithMany("FahrerImTrainings")
                        .HasForeignKey("FahrerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_fahrer_im_training_fahrer");

                    b.HasOne("OpenSlalom.Data.Entities.Training", "Training")
                        .WithMany("FahrerImTrainings")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_fahrer_im_training_training");

                    b.Navigation("Fahrer");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Kart", b =>
                {
                    b.HasOne("OpenSlalom.Data.Entities.Disziplin", "Disziplin")
                        .WithMany("Karts")
                        .HasForeignKey("DisziplinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_karts_disziplin");

                    b.HasOne("OpenSlalom.Data.Entities.Verein", "Verein")
                        .WithMany("Karts")
                        .HasForeignKey("VereinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_karts_vereine");

                    b.Navigation("Disziplin");

                    b.Navigation("Verein");
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Training", b =>
                {
                    b.HasOne("OpenSlalom.Data.Entities.Disziplin", "Disziplin")
                        .WithMany("Trainings")
                        .HasForeignKey("DisziplinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_training_disziplin");

                    b.HasOne("OpenSlalom.Data.Entities.Verein", "Verein")
                        .WithMany("Trainings")
                        .HasForeignKey("VereinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_training_vereine");

                    b.HasOne("OpenSlalom.Data.Entities.Wetter", "Wetter")
                        .WithMany("Trainings")
                        .HasForeignKey("WetterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_training_wetter");

                    b.Navigation("Disziplin");

                    b.Navigation("Verein");

                    b.Navigation("Wetter");
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Trunde", b =>
                {
                    b.HasOne("OpenSlalom.Data.Entities.Tstint", "Tstint")
                        .WithMany("Trunden")
                        .HasForeignKey("TstintId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_trunden_tstints");

                    b.Navigation("Tstint");
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Tstint", b =>
                {
                    b.HasOne("OpenSlalom.Data.Entities.Fahrer", "Fahrer")
                        .WithMany("Tstints")
                        .HasForeignKey("FahrerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tstints_fahrer");

                    b.HasOne("OpenSlalom.Data.Entities.Training", "Training")
                        .WithMany("Tstints")
                        .HasForeignKey("TrainingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_tstints_training");

                    b.Navigation("Fahrer");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Disziplin", b =>
                {
                    b.Navigation("Karts");

                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Fahrer", b =>
                {
                    b.Navigation("FahrerImTrainings");

                    b.Navigation("Tstints");
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Training", b =>
                {
                    b.Navigation("FahrerImTrainings");

                    b.Navigation("Tstints");
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Tstint", b =>
                {
                    b.Navigation("Trunden");
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Verein", b =>
                {
                    b.Navigation("Fahrer");

                    b.Navigation("Karts");

                    b.Navigation("Trainings");
                });

            modelBuilder.Entity("OpenSlalom.Data.Entities.Wetter", b =>
                {
                    b.Navigation("Trainings");
                });
#pragma warning restore 612, 618
        }
    }
}
